GENERATORS/SAMPLE_DATASETS/R_DATASET/R_DATASET.py
GENERATORS/SAMPLE_IMAGES/SKLEARN_IMAGE/SKLEARNIMAGE.py
MANIFEST/r_dataset.manifest.yaml
MANIFEST/table_plotly.manifest.yaml
VISUALIZERS/PLOTLY/TABLE/TABLE.py

Retrieves a pandas DataFrame from `rdatasets` using the provided dataset_key parameter and returns it wrapped in a DataContainer.
creates a Plotly table visualization for a given input `DataContainer` class of type 'dataframe'.
Takes only one input named `dataset_key` which is the name of the dataset to retrieve from `rdatasets`. The default is 'iris'.
https://github.com/flojoy-io/apps/pull/8
- Click on `+ Add Node` button in the SCRIPT tab.
- Expand 'Generators'
- Expand 'Sample datasets'
- Click on 'R Dataset' to add this node to the flow chart
- Click on `+ Add Node` button in the SCRIPT tab.
- Expand 'Visualizers'
- Expand 'Plotly'
- Click on 'Table' to add this node to the flow chart
closes #27 
Corresponding PR in studio: https://github.com/flojoy-io/studio/pull/370

new node: R Dataset, Table

---

VISUALIZERS/PLOTLY/BAR/BAR.py
VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
VISUALIZERS/PLOTLY/LINE/LINE.py
VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
VISUALIZERS/PLOTLY/TABLE/TABLE.py

Updated plot visual nodes to accept `dataframe` type of `DataContainer` class.
corresponding studio PR: https://github.com/flojoy-io/studio/pull/376

update plotly viz nodes to accept dataframe

---

GENERATORS/SAMPLE_DATASETS/PLOTLY_DATASET/PLOTLY_DATASET.py
MANIFEST/plotly_dataset.manifest.yaml

Retrieves a pandas DataFrame from plotly sample datasets using the provided dataset_key parameter and returns it wrapped in a DataContainer.
Takes only one input named `dataset_key` which is the name of the dataset to retrieve from plotly sample datasets. The default is 'wind'.
https://github.com/flojoy-io/apps/pull/9
- Click on `+ Add Node` button in the SCRIPT tab.
- Expand 'Generators'
- Expand 'Sample datasets'
- Click on 'Plotly Dataset' to add this node to the flow chart
closes #28  
Corresponding PR in studio: https://github.com/flojoy-io/studio/pull/375

new node: Plotly Dataset

---

INSTRUMENTS/Serial/Serial_timeseries/SERIAL_TIMESERIES.py
MANIFEST/serial_timeseries.manifest.yaml

Reorganizing serial nodes to allow for multiple serial nodes. Renaming serial to serial_timeseries.
No inputs. Time series outputs with multiple columns of y data possible
https://github.com/flojoy-io/apps/pull/10
Already integrated. Renaming the node to allow for more serial nodes.

Reorganizing serial nodes

---

INSTRUMENTS/Serial/Serial_timeseries/SERIAL_SINGLE_MEAUREMENT.py
MANIFEST/serial_single_measurement.manifest.yaml

Description
SERIAL_SINGLE_MEASUREMENT takes a single reading from a serial device (one or multiple columns).
Inputs & Outputs
No input. y outputs a numpy array for >1 data columns or a list for 1 column.
Example APPS
None yet. Works with SERIAL_TIMESERIES app if replacing SERIAL_TIMESERIES nodes.
Integrating the Node
Similar to SERIAL_TIMESERIES, the SELECT_COLUMN node must be used if there are multiple data columns (e.g. temperature and pressure).

Add single measurement node

---

TRANSFORMERS/ARITHMETIC/SUBTRACT/app.txt
TRANSFORMERS/ARITHMETIC/SUBTRACT/example.md

This PR adds a labelled example app for the Subtract node.

add an example for subtract

---

GENERATORS/SIMULATIONS/TIMESERIES/TIMESERIES.py

pd.testing is only available in pandas 2.X. Until flojoy marks that as a dependency, use `pd.util.testing`

use `pd.util.testing` until flojoy requires pandas 2.X

---

MANIFEST/divide.manifest.yaml
TRANSFORMERS/ARITHMETIC/DIVIDE/app.txt
TRANSFORMERS/ARITHMETIC/DIVIDE/example.md

This PR corrects the manifest for the `DIVIDE` node, and introduces an example

Add an example for `DIVIDE`, fix divide params in manifest

---

ARITHMETIC/ABS.py
ARITHMETIC/__init__.py

This node is redundant given what's in the https://github.com/flojoy-io/nodes/tree/main/TRANSFORMERS/ARITHMETIC directory already.

Removes a redundant ABS node

---

AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/NLP_CONNECT_VIT_GPT2.py
AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/app.txt
AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/example.md
MANIFEST/nlp_connect_vit_gpt2.manifest.yaml

This node calls the nlp-connect ViT GPT2 model for image captioning on an input image, and produces a Dataframe with a "caption" column containing the output. 
P.S: Do Datacontainers support plain python dictionaries?
This PR is dependent on the merge and push of [this PR](https://github.com/flojoy-io/python/pull/41)

add NLP_CONNECT_VIT_GPT2 node

---

.github/workflows/create-studio-docs-pr.yml
create_pr

- Fixed a bug in Get last commit message step on PR closed event.
- I have added a condition for the first "Get Last Commit Message" step to check if the pull request is not merged. So it will checkout to the branch where PR was created and get the commit message from the last commit.
- I have added another step for getting last commit message when PR is merged. So it'll checkout to main branch and retrieve the commit message from last commit made on main branch.
- Updated create pr script to not throw error if last commit message is an empty string.
- The changes appear to be theoretically correct since [this](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository) document suggests the possibility of …

Fixed a bug in CI workflow

---

requirements.txt

Drop an old requirement that is breaking ci/cd
To test I made a virtual env and pip installed everything
```
scorinaldi@donae2:~/projects/flowjoi/nodes$ mkvirtualenv fj_throw
created virtual environment CPython3.10.6.final.0-64 in 385ms
creator CPython3Posix(dest=/home/scorinaldi/.virtualenvs/fj_throw, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/scorinaldi/.local/share/virtualenv)
added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /home/scorinaldi/.virtualenvs/fj_throw/bin/predeactivate …
```

remove deprecated req

---

MANIFEST/countvec.manifest.yaml

Fixing an error in the named manifest file

`Count Vectorizer` key should match name of function class

---

TRANSFORMERS/ARITHMETIC/ABS/ABS.py
TRANSFORMERS/ARITHMETIC/ABS/ABS_test_.py
TRANSFORMERS/ARITHMETIC/ADD/ADD.py
TRANSFORMERS/ARITHMETIC/DIVIDE/DIVIDE.py
TRANSFORMERS/ARITHMETIC/DIVIDE/DIVIDE_test_.py
TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY_test_.py
TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT.py
TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT_test_.py

Inclusion of scalar data type to arthimatic nodes

---

AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/NLP_CONNECT_VIT_GPT2.py
AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/NLP_CONNECT_VIT_GPT2_test_.py
requirements.txt

Move `NL_CONNECT_VIT_GPT2` out of `flojoy.hflib`

---

.github/workflows/pytest-slow-nightly.yml
AI_ML/TEXT_SUMMARIZATION/BART_LARGE_CNN/BART_LARGE_CNN_test_.py

Move tests marked as "slow" to run only once a day every day at midnight UTC

Move all slow tests to run at midnight UTC

---

.github/workflows/pytest-slow-nightly.yml
AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/NLP_CONNECT_VIT_GPT2.py
AI_ML/IMAGE_CAPTIONING/NLP_CONNECT_VIT_GPT2/NLP_CONNECT_VIT_GPT2_test_.py
AI_ML/PREDICT_TIME_SERIES/PROPHET_PREDICT/PROPHET_PREDICT_test_.py
AI_ML/SEGMENTATION/DEEPLAB_V3/DEEPLAB_V3.py
AI_ML/SEGMENTATION/DEEPLAB_V3/DEEPLAB_V3_test_.py
AI_ML/TEXT_SUMMARIZATION/BART_LARGE_CNN/BART_LARGE_CNN_test_.py
EXTRACTORS/FILE/OPEN_IMAGE/OPEN_IMAGE_test_.py
EXTRACTORS/FILE/OPEN_PARQUET/OPEN_PARQUET_test_.py
EXTRACTORS/FILE/READ_S3/READ_S3_test_.py
LOADERS/LOCAL_FILE_SYSTEM/OPEN_MATLAB/OPEN_MATLAB_test_.py
VISUALIZERS/PLOTLY/PROPHET_COMPONENTS/PROPHET_COMPONENTS_test_.py
VISUALIZERS/PLOTLY/PROPHET_PLOT/PROPHET_PLOT_test_.py
conftest.py
node_styleguide.md
requirements.txt

This PR fixes the issue with hanging github runners. Github actions runners (especially mac) would hang when they run out of disk space, and that is because the models these tests download are very large.
We introduce `cleanup_flojoy_cache_fixture` that records file/folder additions to the `~/.flojoy` cache directory and cleans them up once every running test completes.
NOTE: The tests currently run every 20mins. I will let them run for about a day to observe if we still experience hangs, then past that the schedule will resume to running once a day at midnight UTC.

Fix slow nightly tests by cleaning per-test cache, WIP

---

.github/workflows/pytest.yml

The explicit caching step is unnecessary when we specify `cache-dependency-path: requirements.txt` in the setup python action

Remove unnecessary pytest caching step, use regular python action caching

---

GENERATORS/SIMULATIONS/RAND/RAND_test_.py

This fixes a failure on `test_RAND_array_value_poisson`:
```
FAILED
GENERATORS/SIMULATIONS/RAND/RAND_test_.py::test_RAND_array_value_poisson
- AssertionError: assert 0.013319999999999999 < 0.01
+  where 0.013319999999999999 = abs((0.98668 - 1))
+    where 0.98668 = <function mean at 0x7fce70b12db0>(array([1, 2, 0, ..., 1, 1, 0]))
+      where <function mean at 0x7fce70b12db0> = np.mean
+      and   array([1, 2, 0, ..., 1, 1, 0]) = Box({'type':
'OrderedPair', 'x': array([    0,     1,     2, ..., 99997, 99998,
99999]), 'y': array([1, 2, 0, ..., 1, 1, 0]), 'extra': None}).y
```
See: https://github.com/flojoy-ai/nodes/actions/runs/6237588170/job/16931517633?pr=299#step:5:820

fix: Relax assertion on `test_RAND_array_value_poisson`

---

GENERATORS/SAMPLE_DATASETS/SCIKIT_LEARN_DATASET/SCIKIT_LEARN_DATASET.py
GENERATORS/SAMPLE_DATASETS/SCIKIT_LEARN_DATASET/SCIKIT_LEARN_DATASET_test_.py
GENERATORS/SAMPLE_DATASETS/SCIKIT_LEARN_DATASET/app.json
GENERATORS/SAMPLE_DATASETS/SCIKIT_LEARN_DATASET/example.md

No more rdatasets
