- LOADERS/LOCAL_FILE.py
- SIMULATIONS/OBJECT_DETECTION.py
- TERMINATORS/END.py
- VISORS/BAR.py
- VISORS/HISTOGRAM.py
- VISORS/IMAGE.py
- VISORS/LINE.py
- VISORS/SCATTER.py
- VISORS/SCATTER3D.py
- VISORS/SURFACE3D.py
- Updated visual nodes to return corresponding `Plot` data.
- Updated `LOCAL_FILE` node to return `image` type of `DataContainer` class with `RGBA` value instead of bytes array.
- Updated `OBJECT_DETECTION` node to return image after processing without writing to local file.
This is the PR corresponding to the PR in the main studio repo: https://github.com/flojoy-io/studio/pull/290
> modify visual nodes to return plotly processed data

- LOADERS/LOCAL_FILE.py
- MANIFEST/line.manifest.yaml
- SIMULATIONS/FEEDBACK.py
- SIMULATIONS/OBJECT_DETECTION.py
- TERMINATORS/END.py
- VISORS/BAR.py
- VISORS/HISTOGRAM.py
- VISORS/IMAGE.py
- VISORS/LINE.py
- VISORS/SCATTER.py
- VISORS/SCATTER3D.py
- VISORS/SURFACE3D.py
Modified nodes in accordance with changes in flojoy python package.
corresponding PR in studio repo: https://github.com/flojoy-io/studio/pull/299
> Process plotly data from backend

- LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
Updated Frontier URL to load measurement to Frontier.
> Update Frontier url for LOADER node

- AI_ML/OBJECT_DETECTION/OBJECT_DETECTION.py
- GENERATORS/SIMULATIONS/CONSTANT/CONSTANT.py
- GENERATORS/SIMULATIONS/FEEDBACK/FEEDBACK.py
- GENERATORS/SIMULATIONS/LINSPACE/LINSPACE.py
- GENERATORS/SIMULATIONS/RAND/RAND.py
- GENERATORS/SIMULATIONS/SECOND_ORDER_SYSTEM/SECOND_ORDER_SYSTEM.py
- GENERATORS/SIMULATIONS/SINE/SINE.py
- GENERATORS/SIMULATIONS/TIMESERIES/TIMESERIES.py
- INSTRUMENTS/Serial/Serial/SERIAL.py
- INSTRUMENTS/WEB_CAM/CAMERA/CAMERA.py
- LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE.py
- LOGIC_GATES/CONDITIONALS/CONDITIONAL.py
- LOGIC_GATES/LOOPS/GOTO.py
- LOGIC_GATES/LOOPS/LOOP.py
- LOGIC_GATES/TERMINATORS/END.py
- LOGIC_GATES/TIMERS/TIMER.py
- TRANSFORMERS/ARITHMETIC/ABS/ABS.py
- TRANSFORMERS/ARITHMETIC/ADD/ADD.py
- TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
- TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT.py
- TRANSFORMERS/MATRIX_MANIPULATION/INVERT/INVERT.py
- TRANSFORMERS/MATRIX_MANIPULATION/MATMUL/MATMUL.py
- TRANSFORMERS/SELECT_ARRAY/SELECT_ARRAY/SELECT_ARRAY.py
- TRANSFORMERS/SIGNAL_PROCESSING/BUTTER/BUTTER.py
- TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR.py
- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
- TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL.py
- VISUALIZERS/PLOTLY/IMAGE/IMAGE.py
- VISUALIZERS/PLOTLY/SCATTER3D/SCATTER3D.py
- VISUALIZERS/PLOTLY/SURFACE3D/SURFACE3D.py
Please include a summary of the newly created nodes and a little description of what the nodes does.
The newly created nodes should include the inputs and Outputs and a little description why its necessary.
You should create one or mutiple example apps with the new nodes. And Link the Example APPS in the PULL REQUEST
It should contain checklist of steps to successfully integrate your node into the framework.
> changed instances of v to dc_inputs

- TRANSFORMERS/ARITHMETIC/ADD/ADD.py
- TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
- VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
- VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
This fixes an issue with the flow of node data with ADD, MULTIPLY, HISTOGRAM.
ADD: Now forwards x data properly.
MULTIPLY: Now forwards x data properly.
HISTOGRAM: Displays y data properly.
SCATTER: Made marker size smaller.
> Fix node data

- VISUALIZERS/PLOTLY/BAR/BAR.py
- VISUALIZERS/PLOTLY/BIG NUMBER/BIG_NUMBER.py
- VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
- VISUALIZERS/PLOTLY/IMAGE/IMAGE.py
- VISUALIZERS/PLOTLY/LINE/LINE.py
- VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
- VISUALIZERS/PLOTLY/SCATTER3D/SCATTER3D.py
- VISUALIZERS/PLOTLY/SURFACE3D/SURFACE3D.py
- VISUALIZERS/PLOTLY/TABLE/TABLE.py
- VISUALIZERS/template.py
corresponding pr in studio: https://github.com/flojoy-io/studio/pull/443
> use plot layout in visual nodes from template

- TRANSFORMERS/ARITHMETIC/ADD/test_node.py
Please include a summary of the newly created nodes and a little description of what the nodes does.
This PR adds a unit test for a node (the ADD node). Tests get invoked by running `pytest` at the root of this repo.
The newly created nodes should include the inputs and Outputs and a little description why its necessary.
n/a
You should create one or mutiple example apps with the new nodes. And Link the Example APPS in the PULL REQUEST
n/a
It should contain checklist of steps to successfully integrate your node into the framework.
n/a
> add a unit test for ADD

- MANIFEST/divide.manifest.yaml
- TRANSFORMERS/ARITHMETIC/DIVIDE/DIVIDE.py
- TRANSFORMERS/ARITHMETIC/DIVIDE/DIVIDE_test_.py
Please include a summary of the newly created nodes and a little description of what the nodes does.
Adds a node for divide, and a unit test
The newly created nodes should include the inputs and Outputs and a little description why its necessary.
Where should this be? I copied the example manifest from here: https://docs.flojoy.io/custom-nodes/creating-custom-node/#creating-the-manifest
You should create one or mutiple example apps with the new nodes. And Link the Example APPS in the PULL REQUEST
It should contain checklist of steps to successfully integrate your node into the framework.
> Create divide node and unit test

- .gitignore
- GENERATORS/SIMULATIONS/CONSTANT/CONSTANT.py
- GENERATORS/SIMULATIONS/LINSPACE/LINSPACE.py
- GENERATORS/SIMULATIONS/SECOND_ORDER_SYSTEM/SECOND_ORDER_SYSTEM.py
- GENERATORS/SIMULATIONS/SINE/SINE.py
- INSTRUMENTS/LABJACK/LABJACKU3/LABJACKU3.py
- INSTRUMENTS/PHIDGET/PHIDGET22/PHIDGET22.py
- INSTRUMENTS/Serial/Serial_timeseries/SERIAL_TIMESERIES.py
- INSTRUMENTS/Stepper_Motor/STEPPER_DRIVER_TIC.py
- INSTRUMENTS/Stepper_Motor/STEPPER_DRIVER_TIC_KNOB.py
- INSTRUMENTS/WEB_CAM/CAMERA/CAMERA.py
- LOGIC_GATES/TIMERS/TIMER.py
- MANIFEST/camera.manifest.yaml
- MANIFEST/image_smoothing.manifest.yaml
- MANIFEST/linspace.manifest.yaml
- MANIFEST/select_array.manifest.yaml
- MANIFEST/serial_timeseries.manifest.yaml
- TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING.py
- TRANSFORMERS/MATRIX_MANIPULATION/INVERT/INVERT.py
- TRANSFORMERS/SELECT_ARRAY/SELECT_ARRAY/SELECT_ARRAY.py
- TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR.py
- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
- TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL.py
- Got rid of all type conversions from param
- Fixed some data types in manifests
- an additional PR to https://github.com/flojoy-io/studio/issues/395
> Got rid of converts and fixed data types in manifest

- MANIFEST/keithley2400.manifest.yaml
- MANIFEST/serial_single_measurement.manifest.yaml
- MANIFEST/serial_timeseries.manifest.yaml
Please include a summary of the newly created nodes and a little description of what the nodes does.
The newly created nodes should include the inputs and Outputs and a little description why its necessary.
You should create one or mutiple example apps with the new nodes. And Link the Example APPS in the PULL REQUEST
It should contain checklist of steps to successfully integrate your node into the framework.
> Fix pip dependency version type

- AI_ML/CLASSIFICATION/ONE_HOT_ENCODING.py
- AI_ML/CLASSIFICATION/app.txt
- AI_ML/CLASSIFICATION/example.md
- MANIFEST/one_hot_encoding.manifest.yaml
> One hot encoding

- LOGIC_GATES/CONDITIONALS/CONDITIONAL.py
- LOGIC_GATES/CONDITIONALS/app.txt
- LOGIC_GATES/CONDITIONALS/example.md
- MANIFEST/conditional.manifest.yaml
> added example and docstring for conditional node

- LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
Signed-off-by: Joey Yu <joey@itsjoeoui.com>
> Adapt streaming to the new frontier

- MANIFEST/array_view.manifest.yaml
- VISUALIZERS/DATA_STRUCTURE/ARRAY_VIEW/ARRAY_VIEW.py
- VISUALIZERS/DATA_STRUCTURE/ARRAY_VIEW/app.txt
- VISUALIZERS/DATA_STRUCTURE/ARRAY_VIEW/example.md
- VISUALIZERS/DATA_STRUCTURE/MATRIX_VIEW/MATRIX_VIEW.py
- VISUALIZERS/DATA_STRUCTURE/MATRIX_VIEW/app.txt
- VISUALIZERS/DATA_STRUCTURE/MATRIX_VIEW/example.md
> ARRAY_VIEW & MATRIX_VIEW node

- GENERATORS/SIMULATIONS/TIMESERIES/TIMESERIES.py
The df will be referenced before assignment since you don't raise an exception in the `except` block.
> [BUG] You can't return the df if there was an exception

- TRANSFORMERS/ARITHMETIC/ABS/app.txt
- TRANSFORMERS/ARITHMETIC/ABS/example.md
Create a labelled example for the `ABS` node
> Example for absolute val node

- MANIFEST/fft.manifest.yaml
- TRANSFORMERS/SIGNAL_PROCESSING/FFT/FFT.py
- TRANSFORMERS/SIGNAL_PROCESSING/FFT/app.txt
- TRANSFORMERS/SIGNAL_PROCESSING/FFT/example.md
> Fast fourier node

- LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
> Update loader node to support down streaming date from Frontier

- GENERATORS/SIMULATIONS/MATRIX/MATRIX.py
- GENERATORS/SIMULATIONS/MATRIX/app.txt
- GENERATORS/SIMULATIONS/MATRIX/example.md
- MANIFEST/matrix.manifest.yaml
> matrix generator

- AI_ML/PREDICT_TIME_SERIES/PROPHET_PREDICT/PROPHET_PREDICT_test_.py
- AI_ML/PREDICT_TIME_SERIES/PROPHET_PREDICT/app.txt
- AI_ML/PREDICT_TIME_SERIES/PROPHET_PREDICT/example.md
- VISUALIZERS/PLOTLY/PROPHET_COMPONENTS/PROPHET_COMPONENTS_test_.py
- VISUALIZERS/PLOTLY/PROPHET_COMPONENTS/app.txt
- VISUALIZERS/PLOTLY/PROPHET_COMPONENTS/example.md
- VISUALIZERS/PLOTLY/PROPHET_PLOT/PROPHET_PLOT_test_.py
- VISUALIZERS/PLOTLY/PROPHET_PLOT/app.txt
- VISUALIZERS/PLOTLY/PROPHET_PLOT/example.md
Added a test, an app.text and an example.md for the 3 nodes `PROPHET_PREDICT`, `PROPHET_PLOT`, and `PROPHET_COMPONENTS`
> tests, app, example for Prophet

- VISUALIZERS/PLOTLY/COMPOSITE/app.txt
- VISUALIZERS/PLOTLY/COMPOSITE/example.md
> added example.md and app.txt

- .github/workflows/create-studio-docs-pr.yml
- VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
- VISUALIZERS/PLOTLY/SCATTER/app.txt
- VISUALIZERS/PLOTLY/SCATTER/example.md
- create_pr
> Docstring and example: SCATTER

- pull_request_template.md
> update the PR template to require testing to add a new node

- AI_ML/REGRESSION/LEAST_SQUARES/LEAST_SQUARES.py
Small PR for removal of print statement
> removed print statement

- GENERATORS/SIMULATIONS/MATRIX/MATRIX.py
- GENERATORS/SIMULATIONS/MATRIX/MATRIX_test.py
- VISUALIZERS/DATA_STRUCTURE/MATRIX_VIEW/MATRIX_VIEW.py
- VISUALIZERS/DATA_STRUCTURE/MATRIX_VIEW/MATRIX_VIEW_test.py
- Adjusted the `matrix` node to generate a different matrice on every run.
- Adjusted the `matrix_view` node to support more flexible shapes.
> modified matrix and matrix_view node

- MANIFEST/big_number.manifest.yml
- VISUALIZERS/PLOTLY/BAR/BAR.py
- VISUALIZERS/PLOTLY/BAR/app.txt
- VISUALIZERS/PLOTLY/BAR/example.md
- VISUALIZERS/PLOTLY/BIG_NUMBER/BIG_NUMBER.py
- VISUALIZERS/PLOTLY/BIG_NUMBER/app.txt
- VISUALIZERS/PLOTLY/BIG_NUMBER/example.md
- VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
- VISUALIZERS/PLOTLY/HISTOGRAM/app.txt
- VISUALIZERS/PLOTLY/HISTOGRAM/example.md
- VISUALIZERS/PLOTLY/LINE/LINE.py
- VISUALIZERS/PLOTLY/LINE/app.txt
- VISUALIZERS/PLOTLY/LINE/example.md
> Update Plotly Viz nodes: BAR, HISTOGRAM, BIG NUMBER, LINE

- MANIFEST/accuracy.manifest.yaml
- MANIFEST/add.manifest.yaml
- MANIFEST/composite_plot.manifest.yaml
- MANIFEST/divide.manifest.yaml
- MANIFEST/multiply.manifest.yaml
- MANIFEST/subtract.manifest.yaml
- MANIFEST/support_vector_machine.manifest.yaml
Just some manifest updates for rendering correct inputs in studio FE
> update inputs for nodes

- GENERATORS/SIMULATIONS/RAND/RAND.py
- LOGIC_GATES/LOOPS/APPEND/APPEND.py
- LOGIC_GATES/LOOPS/APPEND/APPEND_test.py
- LOGIC_GATES/LOOPS/APPEND/app.txt
- LOGIC_GATES/LOOPS/APPEND/example.md
- MANIFEST/append.manifest.yaml
> APPEND node + RAND changes

- VISUALIZERS/PLOTLY/TABLE/TABLE.py
- VISUALIZERS/PLOTLY/TABLE/app.txt
- VISUALIZERS/PLOTLY/TABLE/example.md
> add example and update docstring for TABLE node

- LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
- LOADERS/REDIS_SYSTEM/REDIS_LOAD/REDIS_LOAD.py
> Loaders nodes jin

- EXTRACTORS/FILE/READ_S3/READ_S3.py
> Updated READ_S3 node

- GENERATORS/SIMULATIONS/CONSTANT/CONSTANT.py
- GENERATORS/SIMULATIONS/LINSPACE/LINSPACE.py
- GENERATORS/SIMULATIONS/RAND/RAND.py
- GENERATORS/SIMULATIONS/SECOND_ORDER_SYSTEM/SECOND_ORDER_SYSTEM.py
- GENERATORS/SIMULATIONS/SINE/SINE.py
- TRANSFORMERS/ARITHMETIC/ABS/ABS.py
- TRANSFORMERS/ARITHMETIC/ABS/ABS_test_.py
- TRANSFORMERS/ARITHMETIC/ADD/ADD.py
- TRANSFORMERS/ARITHMETIC/DIVIDE/DIVIDE.py
- TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
- TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY_test_.py
- TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT.py
- TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT_test_.py
- TRANSFORMERS/ARITHMETIC/utils/arithmetic_utils.py
- TRANSFORMERS/CALCULUS/DIFFERENTIATE/DIFFERENTIATE.py
- TRANSFORMERS/SIGNAL_PROCESSING/TWO_DIMENSIONAL_FFT/TWO_DIMENSIONAL_FFT.py
> added vector type support for nodes

- GENERATORS/SIMULATIONS/RAND/RAND.py
- conftest.py
For https://github.com/flojoy-io/studio/pull/705
> Example docstring for parsing by studio

- INSTRUMENTS/KEITHLEY/KEITHLEY2400/KEITHLEY2400.py
- INSTRUMENTS/SERIAL/SERIAL_SINGLE_MEASUREMENT/SERIAL_SINGLE_MEASUREMENT.py
Added vector input for Keithley node
> Update Keithley node

- GENERATORS/SIMULATIONS/WAVEPACKET/WAVEPACKET.py
- GENERATORS/SIMULATIONS/WAVEPACKET/WAVEPACKET_test_.py
- GENERATORS/SIMULATIONS/WAVEPACKET/app.txt
> Dallas add wavepacket node

- TRANSFORMERS/SIGNAL_PROCESSING/BUTTER/BUTTER_test_.py
- TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR_test_.py
- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID_test_.py
- TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL_test_.py
> Add pytests to signal processing nodes

- TRANSFORMERS/IMAGE_PROCESSING/EDGE_DETECTION/EDGE_DETECTION_test_.py
- TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING.py
- TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING_test_.py
- TRANSFORMERS/MATRIX_MANIPULATION/INVERT/INVERT_test_.py
- TRANSFORMERS/MATRIX_MANIPULATION/MATMUL/MATMUL_test_.py
Also includes assert statements to check for odd kernel sizes in image_smoothing
> Unit tests - matrix image processing

- LOGIC_GATES/TIMERS/TIMER/TIMER.py
- VISUALIZERS/DATA_STRUCTURE/TEXT_VIEW/TEXT_VIEW.py
> Added new viz node TEXT_VIEW

- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID_test_.py
Quick fix correcting the PID formula
> Fix PID node behavior

- .github/workflows/create-docs-pr.yml
- TRANSFORMERS/CALCULUS/DIFFERENTIATE/DIFFERENTIATE.py
- TRANSFORMERS/CALCULUS/DOUBLE_DEFINITE_INTEGRAL/DOUBLE_DEFINITE_INTEGRAL.py
- TRANSFORMERS/CALCULUS/INTEGRATE/INTEGRATE.py
- write_doc.py
- Enabled creating docs PR to update app.txt and python_code.txt file
- Refactored some node functions
> refactored some functions and enable doc PR with app.txt file

- TRANSFORMERS/IMAGE_PROCESSING/EDGE_DETECTION/EDGE_DETECTION.py
- TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING.py
- TRANSFORMERS/SIGNAL_PROCESSING/BUTTER/BUTTER.py
- TRANSFORMERS/SIGNAL_PROCESSING/FFT/FFT.py
- TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR.py
- TRANSFORMERS/SIGNAL_PROCESSING/IFFT/IFFT.py
- TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
- TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL.py
- TRANSFORMERS/SIGNAL_PROCESSING/TWO_DIMENSIONAL_FFT/TWO_DIMENSIONAL_FFT.py
> Mostly adding docstring inputs

- EXTRACTORS/DATAFRAME/EXTRACT_COLUMNS/EXTRACT_COLUMNS.py
- EXTRACTORS/FILE/OPEN_IMAGE/OPEN_IMAGE.py
- EXTRACTORS/FILE/OPEN_PARQUET/OPEN_PARQUET.py
- EXTRACTORS/FILE/READ_CSV/READ_CSV.py
- EXTRACTORS/FILE/READ_S3/READ_S3.py
- LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE/LOCAL_FILE.py
- LOADERS/LOCAL_FILE_SYSTEM/OPEN_MATLAB/OPEN_MATLAB.py
> Format dosctrings for extractor nodes

- TRANSFORMERS/CALCULUS/DOUBLE_DEFINITE_INTEGRAL/example.md
- TRANSFORMERS/MATRIX_MANIPULATION/INVERT/example.md
- TRANSFORMERS/TYPE_CASTING/DF_2_ORDEREDTRIPLE/app.txt
- TRANSFORMERS/TYPE_CASTING/DF_2_ORDEREDTRIPLE/example.md
> Fix math examples description

- LOADERS/CLOUD_DATABASE/FLOJOY_CLOUD_DOWNLOAD/FLOJOY_CLOUD_DOWNLOAD.py
- LOADERS/CLOUD_DATABASE/FLOJOY_CLOUD_UPLOAD/FLOJOY_CLOUD_UPLOAD.py
Requires https://github.com/flojoy-ai/python/pull/84
> Update imports and var name for cloud nodes

- TRANSFORMERS/IMAGE_PROCESSING/EDGE_DETECTION/EDGE_DETECTION.py
- TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING.py
quick PR to get default image processing apps working
> add dependencies to image nodes

- LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE/LOCAL_FILE.py
corresponding pr in studio: https://github.com/flojoy-ai/studio/pull/885
> Remove lxml dep from local file and handle relative path

- TRANSFORMERS/CALCULUS/DOUBLE_INDEFINITE_INTEGRAL/app.json
- TRANSFORMERS/TYPE_CASTING/DF_2_NP/app.json
- TRANSFORMERS/TYPE_CASTING/DF_2_ORDERED_TRIPLE/app.json
- VISUALIZERS/PLOTLY/LINE/app.json
- VISUALIZERS/PLOTLY/TABLE/app.json
> Dallas update apps rdata
